# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad1248e5d6f6568b8251358d1017abadd371a6d626ccaa9fb23e7f9d0dcb7e204b1ca90cf0b981a5582c41d3aad01e7cfef5b599baed9da45e873ba495d4658e

test:
  secret_key_base: 353fcab62df5f9203ad5cef283d76886036b666eebe651c7ddfced5db9527ad7e874bddd40114de3426acf5470fb3080b7cd8a78ebe1d244d58b4d50d82022f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
